### PR TITLE
Remove extra logging, move param methods from api, other fixes

### PR DESCRIPTION
**Pull request by rvegas**

### CODE REVIEW

**Comment by rvegas** [comment]
I've added tests that were declared but unimplemented. Locally the coverage increased a little. Let's wait for Lord Travis.

**Comment by orestes** [comment]
Fine by me, but I don't get extracting the param-related methods out of API if we're going to duplicate them in the derived classes that are using them.
If you don't think that's a bit of a step back, let's merge this.

**Comment by rvegas** [comment]
The thing is that the `Response` objects can't get access to Params as per Specification.

**Comment by rvegas** [comment]
From here: https://github.com/kusanagi/katana-sdk-spec#72-response

`Response` should not be able to call `getParam`, `getParams()`, `hasParam()` and so on. Whereas `Request` may do, see here: https://github.com/kusanagi/katana-sdk-spec#71-request

**Comment by orestes** [comment]
`Response` is extending `Api`, it has access to the params via `hasParam`, `getParam`, `getParams` through the base class implementation.

**Comment by rvegas** [comment]
`Response` MAY extend `Api`, but must not have access to the params.

**Comment by orestes** [comment]
Okay, this little duplication makes sense in the current context.

**Pull request merged**
